CREATE DATABASE IF NOT EXISTS BD_BIBLIOTECA_DIGITAL_2ANO;
USE BD_BIBLIOTECA_DIGITAL_2ANO;

CREATE TABLE IF NOT EXISTS AUTOR(
	CPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255),
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS LEITOR(
	CPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    GENERO_PREFERIDO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255),
    FOTO BLOB,
    GENERO VARCHAR(255),
    FK_CPF_AUTOR VARCHAR(15) NOT NULL,
    FOREIGN KEY (FK_CPF_AUTOR) REFERENCES AUTOR(CPF) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ACESSAR(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_LIVRO_DIGITAL INTEGER,
    FK_CPF_LEITOR VARCHAR(15) NOT NULL,
    FOREIGN KEY (FK_ID_LIVRO_DIGITAL) REFERENCES LIVRO_DIGITAL (ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_LEITOR) REFERENCES LEITOR(CPF) ON DELETE CASCADE
);