CREATE DATABASE IF NOT EXISTS BD_CONSULTAS_MEDICAS_2ANO;
USE BD_CONSULTAS_MEDICAS_2ANO;

CREATE TABLE IF NOT EXISTS MEDICO(
	CRM VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255),
    FORMACAO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PACIENTE(
	CPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    MOTIVO VARCHAR(444) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONSULTAS(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(255) NOT NULL,
    ENDERECO VARCHAR(255) NOT NULL,
    DATA_CONSULTA DATE,
    FK_CRM_MEDICO VARCHAR(20) NOT NULL,
    FK_CPF_PACIENTE VARCHAR(15) NOT NULL,
    FOREIGN KEY (FK_CRM_MEDICO) REFERENCES MEDICO(CRM) ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_PACIENTE) REFERENCES PACIENTE(CPF) ON DELETE CASCADE
);
