CREATE DATABASE IF NOT EXISTS BD_ENQUETES_2ANO;
USE BD_ENQUETES_2ANO;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_CODIGO INTEGER AUTO_INCREMENT,
    USU_DATA_CADASTRO DATE NOT NULL,
    USU_LOGIN VARCHAR(255) NOT NULL UNIQUE,
    USU_AREA_ATUACAO VARCHAR(500),
    USU_PROFISSAO VARCHAR(200),
    USU_ARERA_FORMACAO VARCHAR(500),
    USU_DATANASC DATE NOT NULL,
    USU_ESTADO_CIVIL ENUM("SOLTEIRIO","CASADO","DIVORCIADO","VIÚVO") NOT NULL,
    USU_ESTASDO VARCHAR(2) NOT NULL,
    USU_ESCOLARIDADE ENUM("FUNDAMENTAL","MEDIO","SUPERIOR") NOT NULL,
    USU_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USU_SENHA VARCHAR(255) NOT NULL,
    USU_NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY(USU_CODIGO)
);

CREATE TABLE IF NOT EXISTS ENQUETE(
	ENQ_CODIGO INTEGER AUTO_INCREMENT,
    ENQ_DATA_FINAL DATE,
    ENQ_DAT_INICIAL DATE NOT NULL,
    ENQ_DESCRICAO VARCHAR(500) NOT NULL,
    ENQ_NOME VARCHAR(255) NOT NULL,
    FK_USU_CODIGO INTEGER NOT NULL,
    PRIMARY KEY(ENQ_CODIGO),
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO(USU_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS USUARIO_RESPONDE_ENQUETE(
	URE_CODIGO INTEGER AUTO_INCREMENT,
    URE_DATA DATE NOT NULL,
    FK_USU_CODIGO INTEGER,
    FK_ENQ_CODIGO INTEGER,
    PRIMARY KEY(URE_CODIGO),
    FOREIGN KEY (FK_USU_CODIGO) REFERENCES USUARIO(USU_CODIGO) ON DELETE CASCADE,
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE(ENQ_CODIGO) ON DELETE CASCADE    
);

CREATE TABLE IF NOT EXISTS PERGUNTAS(
	PER_CODIGO INTEGER AUTO_INCREMENT,
    PER_DESCRICAO VARCHAR(255) NOT NULL UNIQUE,
    FK_ENQ_CODIGO INTEGER NOT NULL,
    PRIMARY KEY(PER_CODIGO),
    FOREIGN KEY (FK_ENQ_CODIGO) REFERENCES ENQUETE(ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESPOSTAS(
	RES_CODIGO INTEGER AUTO_INCREMENT,
    RES_DESCRICAO VARCHAR(255) NOT NULL UNIQUE,
    RES_CERTA VARCHAR(1) NOT NULL,
    FK_PER_CODIGO INTEGER NOT NULL,
    PRIMARY KEY(RES_CODIGO),
    FOREIGN KEY (FK_PER_CODIGO) REFERENCES PERGUNTAS(PER_CODIGO) ON DELETE CASCADE
);

INSERT INTO USUARIO (USU_DATA_CADASTRO,USU_LOGIN,USU_AREA_ATUACAO,USU_PROFISSAO,USU_ARERA_FORMACAO,USU_DATANASC,USU_ESTADO_CIVIL,USU_ESTASDO,USU_ESCOLARIDADE,USU_EMAIL,USU_SENHA,USU_NOME)
VALUES ("2025-10-01","maria.clara","T.I","Analista de Sistemas","Ciência da Computação","2009-04-08","SOLTEIRIO","SP","MEDIO","maria.clara@example.com","Senha@123","Maria Clara Braga");

INSERT INTO USUARIO (USU_DATA_CADASTRO,USU_LOGIN,USU_AREA_ATUACAO,USU_PROFISSAO,USU_ARERA_FORMACAO,USU_DATANASC,USU_ESTADO_CIVIL,USU_ESTASDO,USU_ESCOLARIDADE,USU_EMAIL,USU_SENHA,USU_NOME)
VALUES ("2025-10-01","joão.silva","Engenheiro Civil","Engenheiro Estrutural","Engenharia Civil","2008-05-10","CASADO","MG","SUPERIOR","joao.silva@example.com","Segura@567","João Pedro da Silva");

INSERT INTO USUARIO (USU_DATA_CADASTRO,USU_LOGIN,USU_AREA_ATUACAO,USU_PROFISSAO,USU_ARERA_FORMACAO,USU_DATANASC,USU_ESTADO_CIVIL,USU_ESTASDO,USU_ESCOLARIDADE,USU_EMAIL,USU_SENHA,USU_NOME)
VALUES ("2025-10-01","ana.oliveira","Marketing Dgigtal","Gestora de Midia","Publicidade e propaganda","1999-10-11","DIVORCIADO","PI","SUPERIOR","ana.oliveira@example.com","MIDIA@123","Ana Rita Oliveira");

SELECT * FROM USUARIO;

INSERT INTO ENQUETE (ENQ_DATA_FINAL,ENQ_DAT_INICIAL,ENQ_DESCRICAO,ENQ_NOME,FK_USU_CODIGO)
VALUES ("2025-12-03","2025-10-01","Como você gosta de aproveitar seu tempo","Tempo de Qualidade",3);

INSERT INTO ENQUETE (ENQ_DATA_FINAL,ENQ_DAT_INICIAL,ENQ_DESCRICAO,ENQ_NOME,FK_USU_CODIGO)
VALUES ("2025-12-30","2025-08-22","As inovações não param de surgir","Inovações do futuro",2);

INSERT INTO ENQUETE (ENQ_DATA_FINAL,ENQ_DAT_INICIAL,ENQ_DESCRICAO,ENQ_NOME,FK_USU_CODIGO)
VALUES ("2026-01-22","2025-05-30","Todo mundo tem um gosto especial","Sabores do momento",1);

SELECT * FROM ENQUETE;

INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA,FK_USU_CODIGO,FK_ENQ_CODIGO)
VALUES ("2026-01-22",1,1);

INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA,FK_USU_CODIGO,FK_ENQ_CODIGO)
VALUES ("2025-01-22",2,2);

INSERT INTO USUARIO_RESPONDE_ENQUETE (URE_DATA,FK_USU_CODIGO,FK_ENQ_CODIGO)
VALUES ("2025-10-01",3,3);

SELECT * FROM USUARIO_RESPONDE_ENQUETE;

INSERT INTO PERGUNTAS (PER_DESCRICAO,FK_ENQ_CODIGO)
VALUES ("Se você pudesse viajar para qualquer lugar do mundo agora, para onde iria e por quê?",1);

INSERT INTO PERGUNTAS (PER_DESCRICAO,FK_ENQ_CODIGO)
VALUES ("Qual foi o último livro ou filme que realmente te marcou?",2);

INSERT INTO PERGUNTAS (PER_DESCRICAO,FK_ENQ_CODIGO)
VALUES ("O que você gostaria de aprender ou melhorar nos próximos meses?",3);

SELECT * FROM PERGUNTAS;

INSERT INTO RESPOSTAS (RES_DESCRICAO,RES_CERTA,FK_PER_CODIGO)
VALUES ("A - Eu iria para o Japão, porque gosto muito da mistura de tradição e tecnologiaadoraria conhecer Kyoto pelos templos e Tóquio pela modernidade ","A",1);

INSERT INTO RESPOSTAS (RES_DESCRICAO,RES_CERTA,FK_PER_CODIGO)
VALUES ("B - O livro Sobre a Revolução da Hannah Arendt ","B",2);

INSERT INTO RESPOSTAS (RES_DESCRICAO,RES_CERTA,FK_PER_CODIGO)
VALUES ("C - Gostaria de melhorar minhas habilidades em programação criativa. ","C",3);

SELECT * FROM RESPOSTAS;

