CREATE DATABASE IF NOT EXISTS BD_GERENCIAMENTO_PROJETOS_2ANO;
USE BD_GERENCIAMENTO_PROJETOS_2ANO;

CREATE TABLE IF NOT EXISTS PROJETO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255),
    CUSTO DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS TAREFA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_TAREFA DATE NOT NULL,
    FK_ID_PROJETO INTEGER,
    FK_CPF_FUNCIONARIO VARCHAR(15) NOT NULL,
    FOREIGN KEY (FK_ID_PROJETO) REFERENCES PROJETO(ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_CPF_FUNCIONARIO) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE
);