CREATE DATABASE IF NOT EXISTS BD_GESTAO_SUPERMERCADO_2ANO;
USE BD_GESTAO_SUPERMERCADO_2ANO;

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(20) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    VALOR DOUBLE NOT NULL,
    FOTO BLOB
);

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(255),
    NOME VARCHAR(255) NOT NULL,
    FK_ID_PRODUTO INTEGER,
    FOREIGN KEY (FK_ID_PRODUTO) REFERENCES PRODUTO(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FORNECE(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_CNPJ_FORNECEDOR VARCHAR(20) NOT NULL,
    FK_ID_PRODUTO INTEGER,
    FOREIGN KEY (FK_CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CNPJ) ON DELETE CASCADE,
    FOREIGN KEY (FK_ID_PRODUTO) REFERENCES PRODUTO(ID) ON DELETE CASCADE
);