CREATE  DATABASE IF NOT EXISTS BD_PASSAGEM_AEREA;
USE BD_PASSAGEM_AEREA;

CREATE TABLE IF NOT EXISTS PASSAGEIRO(
	CPF VARCHAR(15) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    IDADE VARCHAR(5) NOT NULL,
    PASSAPORTE VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS ASSENTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CONFORTO BLOB,
    ACESSIBILIDADE VARCHAR(100),
    FK_CPF_PASSAGEIRO VARCHAR(15) NOT NULL,
    FOREIGN KEY (FK_CPF_PASSAGEIRO) REFERENCES PASSAGEIRO(CPF) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS VOO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESTINO VARCHAR(255) NOT NULL,
    CLASSE VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(255),
    FK_ID_ASSENTO INTEGER,
    FOREIGN KEY (FK_ID_ASSENTO) REFERENCES ASSENTO(ID) ON DELETE CASCADE
);