CREATE DATABASE IF NOT EXISTS BD_STREAMING_VIDEO_2ANO;
USE BD_STREAMING_VIDEO_2ANO;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    IDADE VARCHAR(5) NOT NULL,
    DESCRICAO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS VIDEO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    TEMPO VARCHAR(200),
    FK_ID_CATEGORIA INTEGER,
    FOREIGN KEY (FK_ID_CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS VIZUALIZACAO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    INTERACAO VARCHAR(500) NOT NULL,
    FK_ID_VIDEO INTEGER,
    FOREIGN KEY (FK_ID_VIDEO) REFERENCES VIDEO(ID) ON DELETE CASCADE
);